apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-rwo
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: do-block-storage
